# Generated by Django 5.2.8 on 2025-11-18 12:33

import django.db.models.deletion
import gestion_carreras.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grado_academico', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('tecnico_superior', 'Técnico Superior'), ('tecnico_medio', 'Técnico Universitario Medio')], default='licenciatura', max_length=20)),
                ('diploma_academico', models.CharField(blank=True, max_length=300)),
                ('tiempo_estudios', models.CharField(blank=True, max_length=100)),
                ('titulo_provision_nacional', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FaseCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('medios_verificacion', models.TextField(blank=True, help_text='Medios de verificación esperados')),
            ],
            options={
                'verbose_name': 'Fase del Cronograma',
                'verbose_name_plural': 'Fases del Cronograma',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_proceso', '🔄 En Proceso'), ('completado', '✅ Completado')], default='pendiente', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('medios_verificacion', models.TextField(blank=True, help_text='Medios de verificación cumplidos')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_carreras.carrera')),
                ('ultimo_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_carreras.fasecronograma')),
            ],
            options={
                'verbose_name': 'Estado del Cronograma',
                'verbose_name_plural': 'Estados del Cronograma',
                'ordering': ['fase__orden'],
                'unique_together': {('carrera', 'fase')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=gestion_carreras.models.archivo_upload_path, verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('acta', 'Acta'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('otro', 'Otro')], default='documento', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del archivo', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del contenido del archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion_carreras.estadocronograma')),
            ],
            options={
                'verbose_name': 'Archivo del Cronograma',
                'verbose_name_plural': 'Archivos del Cronograma',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_carreras.facultad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_carreras.sede'),
        ),
    ]
